name: Create Jira issue on PR open
on:
  pull_request:
    types: [ opened, review_requested ]
  pull_request_review:
    types: [ submitted ]
jobs:
  create_jira_issue:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get secrets
        uses: hashicorp/vault-action@v2.4.0
        id: secrets
        with:
          url: https://vault.dev.growave.io
          method: jwt
          role: github-workflow
          secrets: |
            engineering/data/production/jira github.integration.apiToken | EV_JIRA_API_TOKEN;
            engineering/data/production/jira github.integration.userEmail | EV_JIRA_USER_EMAIL;
            engineering/data/production/jira github.integration.projectKey | EV_JIRA_PROJECT_KEY;
            engineering/data/production/jira github.integration.url | EV_JIRA_URL;
            engineering/data/production/jira github.integration.issueType | EV_JIRA_ISSUE_TYPE;
            engineering/data/production/jira github.integration.subIssueType | EV_JIRA_SUB_ISSUE_TYPE;
            engineering/data/production/jira github.mapping | EV_JIRA_GITHUB_MAPPING;
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get PR details
        id: pr-details
        run: |
          echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo 'DESCRIPTION<<EOF' >> $GITHUB_OUTPUT
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          echo "assignee=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "reviewers=${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}" >> $GITHUB_OUTPUT
      - name: Create Jira issue for assignee
        id: create-assigned-issue
        env:
          DESCRIPTION: ${{ steps.pr-details.outputs.description }}
          ASSIGNEE: ${{ steps.pr-details.outputs.assignee }}
          PR_NUMBER: ${{ steps.pr-details.outputs.number }}
          PR_TITLE: ${{ steps.pr-details.outputs.title }}
        run: |
          key=${{ env.ASSIGNEE }}
          echo "ASSIGNEE: ${ASSIGNEE}"
          assignee_id=$(echo '${{ env.EV_JIRA_GITHUB_MAPPING }}' | jq -r --arg key "${{ env.ASSIGNEE }}" '.[$key]')
          echo "ASSIGNEE ID: ${assignee_id}"
          echo "DESCRIPTION: ${{ env.DESCRIPTION }}"
          #Find all fields
          curl -s --request GET \
          --url "${{ env.EV_JIRA_URL }}/rest/api/3/field" \
          --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
          --header "Content-Type: application/json" > all_fields.json
          git fetch origin master
          lines_changed=$(git diff --shortstat origin/master HEAD | awk '{print $1 + $4}')
          files_changed=$(curl -s --request GET \
          --url "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.v3+json" | jq '. | length')
          files_changed_field_id=$(jq -r --arg name "files_changed" '.[] | select(.name == "files_changed") | .id' all_fields.json)
          lines_changed_field_id=$(jq -r --arg name "lines_changed" '.[] | select(.name == "lines_changed") | .id' all_fields.json)
          echo "lines_changed = ${lines_changed}"
          echo "files_changed = ${files_changed}"
          echo "files_changed_field_id = ${files_changed_field_id}"
          echo "lines_changed_field_id = ${lines_changed_field_id}"
          description=$(echo "${{ env.DESCRIPTION }}" | jq -sR '.')
          curl -s -X POST \
          --url "${{ env.EV_JIRA_URL }}/rest/api/3/issue/" \
          --header "Content-Type: application/json" \
          --header "Accept: application/json" \
          --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
          --data '{
            "fields": {
              "project": {
                "key": "'"${{ env.EV_JIRA_PROJECT_KEY }}"'"
              },
              "issuetype": {
                "name": "'"${{ env.EV_JIRA_ISSUE_TYPE }}"'"
              },
              "summary": "'"${GITHUB_REPOSITORY#${GITHUB_OWNER}}#${PR_NUMBER} - ${PR_TITLE}"'",
              "description": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": '"${description}"'
                      }
                    ]
                  }
                ]
              },
              "assignee": {
                "accountId": "'"${assignee_id}"'"
              },
              "'"${files_changed_field_id}"'": '${files_changed}',
              "'"${lines_changed_field_id}"'": '${lines_changed}'
            }
          }' > jira-issue.json
          
          # Parse issue key from Jira response
          cat jira-issue.json
          assignee_issue_key=$(cat jira-issue.json | jq -r '.key')
          echo "assignee-issue-key=${assignee_issue_key}" >> $GITHUB_OUTPUT
      - name: Create Jira issues for reviewers
        env:
          REVIEWERS: ${{ steps.pr-details.outputs.reviewers }}
          ASSIGNEE_ISSUE_KEY: ${{ steps.create-assigned-issue.outputs.assignee-issue-key }}
          PR_NUMBER: ${{ steps.pr-details.outputs.number }}
          PR_TITLE: ${{ steps.pr-details.outputs.title }}
        run: |
          for reviewer in $(echo ${{ env.REVIEWERS }} | tr ',' '\n'); do
            key=${reviewer}
            reviewer_id=$(echo '${{ env.EV_JIRA_GITHUB_MAPPING }}' | jq -r --arg key "${reviewer}" '.[$key]')
            echo "Reviewer: ${reviewer_id}"
            curl -s -X POST \
            --url "${{ env.EV_JIRA_URL }}/rest/api/2/issue/" \
            --header "Content-Type: application/json" \
            --header "Accept: application/json" \
            --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
            --data '{
              "fields": {
                "project": {
                  "key": "'"${{ env.EV_JIRA_PROJECT_KEY }}"'"
                },
                "parent": {
                  "key": "'"${{ env.ASSIGNEE_ISSUE_KEY }}"'"
                },
                "issuetype": {
                  "name": "'"${{ env.EV_JIRA_SUB_ISSUE_TYPE }}"'"
                },
                "summary": "'"${GITHUB_REPOSITORY#${GITHUB_OWNER}}#${PR_NUMBER} - ${PR_TITLE} - Reviewed by ${reviewer}"'",
                "assignee": {
                  "accountId": "'"${reviewer_id}"'"
                }
              }
            }' > jira-subtask.json
            cat jira-subtask.json
            SUBTASK_KEY=$(cat jira-subtask.json | jq -r '.key')
          done
  add_reviewer:
    if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REVIEWER_LOGIN: ${{ github.event.review.user.login }}
      ASSIGNEE_LOGIN: ${{ github.event.pull_request.user.login }}
    steps:
      - name: Get secrets
        uses: hashicorp/vault-action@v2.4.0
        id: secrets
        with:
          url: https://vault.dev.growave.io
          method: jwt
          role: github-workflow
          secrets: |
            engineering/data/production/jira github.integration.apiToken | EV_JIRA_API_TOKEN;
            engineering/data/production/jira github.integration.userEmail | EV_JIRA_USER_EMAIL;
            engineering/data/production/jira github.integration.projectKey | EV_JIRA_PROJECT_KEY;
            engineering/data/production/jira github.integration.url | EV_JIRA_URL;
            engineering/data/production/jira github.mapping | EV_JIRA_GITHUB_MAPPING;
      - name: Search
        id: search
        uses: tomhjp/gh-action-jira-search@v0.2.2
        env:
          JIRA_BASE_URL: ${{ secrets.EV_JIRA_URL }}
          JIRA_USER_EMAIL: ${{ env.EV_JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ env.EV_JIRA_API_TOKEN }}
        with:
          jql: 'project = "${{ env.EV_JIRA_PROJECT_KEY }}" AND text ~ "#${{ env.PR_NUMBER }} "'
      - name: Log
        run: echo "Found issue ${{ steps.search.outputs.issue }}"
      - name: Create reviewer subtask
        run: |
          current_time=$(date +%s)
          pr_created_at=$(jq -r '.pull_request.created_at' "$GITHUB_EVENT_PATH")
          current_time_seconds=$(date -d "$current_time" +%s)
          pr_created_at_seconds=$(date -d "$pr_created_at" +%s)
          time_difference=$((current_time_seconds - pr_created_at_seconds))
          if ((time_difference <= 2)); then 
            echo "PR just created."
            exit 1
          fi
          key=${{ env.REVIEWER_LOGIN }}
          reviewer_id=$(echo '${{ env.EV_JIRA_GITHUB_MAPPING }}' | jq -r --arg key "${{ env.REVIEWER_LOGIN }}" '.[$key]')
          echo "Reviewer: ${reviewer_id}"
          curl -s -X POST \
          --url "${{ env.EV_JIRA_URL }}/rest/api/2/issue/" \
          --header "Content-Type: application/json" \
          --header "Accept: application/json" \
          --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
          --data '{
            "fields": {
              "project": {
                "key": "'"${{ env.EV_JIRA_PROJECT_KEY }}"'"
              },
              "parent": {
                "key": "'"${{ steps.search.outputs.issue }}"'"
              },
              "issuetype": {
                "name": "'"${{ env.EV_JIRA_SUB_ISSUE_TYPE }}"'"
              },
              "summary": "'"${GITHUB_REPOSITORY#${GITHUB_OWNER}}#${PR_NUMBER} - ${PR_TITLE} - Reviewed by ${reviewer}"'",
              "assignee": {
                "accountId": "'"${reviewer_id}"'"
              }
            }

  update_subtasks:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REVIEWER_LOGIN: ${{ github.event.review.user.login }}
      ASSIGNEE_LOGIN: ${{ github.event.pull_request.user.login }}
    steps:
      - name: Get secrets
        uses: hashicorp/vault-action@v2.4.0
        id: secrets
        with:
          url: https://vault.dev.growave.io
          method: jwt
          role: github-workflow
          secrets: |
            engineering/data/production/jira github.integration.apiToken | EV_JIRA_API_TOKEN;
            engineering/data/production/jira github.integration.userEmail | EV_JIRA_USER_EMAIL;
            engineering/data/production/jira github.integration.projectKey | EV_JIRA_PROJECT_KEY;
            engineering/data/production/jira github.integration.url | EV_JIRA_URL;
            engineering/data/production/jira github.mapping | EV_JIRA_GITHUB_MAPPING;
      - name: Get reviewer ID
        id: get-reviewer-id
        run: |
          key=${{ env.REVIEWER_LOGIN }}
          echo "assignee=${{ env.ASSIGNEE_LOGIN }}" >> $GITHUB_OUTPUT
          reviewer_id=$(echo '${{ env.EV_JIRA_GITHUB_MAPPING }}' | jq -r --arg key "${{ env.REVIEWER_LOGIN }}" '.[$key]')
          echo "reviewer_id=${reviewer_id}" >> $GITHUB_ENV
          echo "reviewer_id=${reviewer_id}"
      - name: Search
        id: search
        uses: tomhjp/gh-action-jira-search@v0.2.2
        env:
          JIRA_BASE_URL: ${{ secrets.EV_JIRA_URL }}
          JIRA_USER_EMAIL: ${{ env.EV_JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ env.EV_JIRA_API_TOKEN }}
        with:
          jql: 'project = "${{ env.EV_JIRA_PROJECT_KEY }}" AND text ~ "#${{ env.PR_NUMBER }} " AND assignee = "${{ env.reviewer_id }}"'
      - name: Log
        run: echo "Found issue ${{ steps.search.outputs.issue }}"
      - name: Get Transition ID
        id: get-transition-id
        run: |
          curl --request GET \
            --url "${{ env.EV_JIRA_URL }}/rest/api/3/issue/${{ steps.search.outputs.issue }}/transitions" \
            --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
            --header "Accept: application/json" > transition.json
          cat transition.json
          transition_id=$(cat transition.json | jq -r '.transitions[] | select(.to.statusCategory.key == "done") | .id')
          echo "transition_id=${transition_id}" >> $GITHUB_ENV
          echo "transition_id = ${transition_id}"
      - name: Change reviewer issue status
        run: |
          curl -s --request POST \
          --url "${{ env.EV_JIRA_URL }}/rest/api/3/issue/${{ steps.search.outputs.issue }}/transitions" \
          --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --data '{
            "transition": {
              "id": "${{ env.transition_id }}"
            },
            "fields": {}
          }' > transition.json
          cat transition.json
      - name: Get changed files
        id: changed-files
        run: echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)" >> $GITHUB_OUTPUT
      - name: Update first or second review time
        run: |
          # Get the pull request number
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "PR_NUMBER=${PR_NUMBER}"
          echo "github repository=${{ github.repository }}"
          REVIEWS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")
          APPROVAL_COUNT_OVERALL=$(echo "${REVIEWS}" | jq '[.[] | select(.state == "APPROVED")] | length')
          APPROVAL_COUNT=$(echo "${REVIEWS}" | jq --arg username "${{ env.REVIEWER_LOGIN }}" '. | map(select(.user.login == $username and .state == "APPROVED")) | length')
          echo "APPROVAL_COUNT=${APPROVAL_COUNT}";
          REVIEWED_REVIEWERS=$(echo "${REVIEWS}" | jq -r '.[].user.login' | sort | uniq | wc -l)
          echo "REVIEWED_REVIEWERS=${REVIEWED_REVIEWERS}";
          
          response=$(curl -s --request GET \
            --url "${{ env.EV_JIRA_URL }}/rest/api/3/issue/${{ steps.search.outputs.issue }}" \
            --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
            --header "Accept: application/json")
          parent_key=$(echo "$response" | jq -r '.fields.parent.key')
          echo "parent_key=${parent_key}"
          
          curl -s --request GET \
            --url "${{ env.EV_JIRA_URL }}/rest/api/3/field" \
            --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
            --header "Content-Type: application/json" > all_fields.json
          
          first_review_time_field_id=$(jq -r --arg name "first_review_time" '.[] | select(.name == "first_review_time") | .id' all_fields.json)
          echo "first_review_time_field_id=${first_review_time_field_id}"
          
          second_review_time_field_id=$(jq -r --arg name "second_review_time" '.[] | select(.name == "second_review_time") | .id' all_fields.json)
          echo "second_review_time_field_id=${second_review_time_field_id}"
          
          # First review - update first_review_time field                    
          response=$(curl -s --request GET \
            --url "${{ env.EV_JIRA_URL }}/rest/api/3/issue/${{ steps.search.outputs.issue }}" \
            --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
            --header "Accept: application/json")
          first_review_time=$(echo "$response" | jq -r ".fields.${first_review_time_field_id}")
          echo "first_review_time=$first_review_time"
          # Second review - update second_review_time field          
          second_review_time=$(echo "$response" | jq -r ".fields.${second_review_time_field_id}")
          echo "second_review_time = ${second_review_time}"
          
          if [ "$((APPROVAL_COUNT))" == 1 ]; then
            if [ "$((REVIEWED_REVIEWERS))" == 1 ]; then
              curl -s --request PUT \
              --url "${{ env.EV_JIRA_URL }}/rest/api/3/issue/${parent_key}" \
              --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              --data '{
                "fields":{
                  "'"${first_review_time_field_id}"'": "'"$(date +'%Y-%m-%dT%H:%M:%S.000%z')"'"
                }
              }'
            fi
            if [ "(($REVIEWED_REVIEWERS))" == 2 ]; then
              curl -s --request PUT \
              --url "${{ env.EV_JIRA_URL }}/rest/api/3/issue/${parent_key}" \
              --user "${{ env.EV_JIRA_USER_EMAIL }}:${{ env.EV_JIRA_API_TOKEN }}" \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              --data '{
                "fields": {
                  "'"${second_review_time_field_id}"'": "'"$(date +'%Y-%m-%dT%H:%M:%S.000%z')"'"
                }
              }'
            fi
          fi
