name: Create Jira issue on PR open
on:
  pull_request:
    types: [opened]
jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        id: pr-details
        run: |
          echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "description=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          echo "assignee=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "reviewers=${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}" >> $GITHUB_OUTPUT
      - name: Create Jira issue
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          ISSUE_TYPE: ${{ secrets.JIRA_ISSUE_TYPE }}
          JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
          DESCRIPTION: ${{ steps.pr-details.outputs.description }}
          ASSIGNEE: ${{ steps.pr-details.outputs.assignee }}
          REVIEWERS: ${{ steps.pr-details.outputs.reviewers }}
          COLLABORATORS_JSON: ${{ secrets.JIRA_GITHUB_MAPPING }}
        run: |
          MAP=$(echo "${COLLABORATORS_JSON}" | jq -r '.mapping')
          echo "MAP: ${MAP}"
          assignee_id=$(jq -r --arg assignee "${steps.pr-details.outputs.assignee}" '.[$ASSIGNEE]' <<<"${MAP}")
          echo "ASSIGNEE ID: ${assignee_id}"
          curl -s -X POST \
          --url "${JIRA_URL}/rest/api/2/issue/" \
          --header "Content-Type: application/json" \
          --header "Accept: application/json" \
          --user "${JIRA_AUTH}" \
          -d '{
            "fields": {
              "project": {
                  "key": "'"${PROJECT_KEY}"'"
              },
              "issuetype": {
                  "name": "'"${ISSUE_TYPE}"'"
              },
              "summary": "'"${{ steps.pr-details.outputs.title }} - ${GITHUB_REPOSITORY#${GITHUB_OWNER}}#${{ steps.pr-details.outputs.number }}"'",
              "description": "'"${DESCRIPTION}"'",
              "assignee": {
                "accountId": "'"${assignee_id}"'"
              }
            }
          }' > jira-issue.json
