name: Create Jira issue on PR open
on:
  pull_request:
    types: [ opened, review_requested ]
  pull_request_review:
    types: [ submitted ]
env:
  JIRA_URL: ${{ secrets.JIRA_URL }}
  PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
  ISSUE_TYPE: ${{ secrets.JIRA_ISSUE_TYPE }}
  SUB_ISSUE_TYPE: ${{ secrets.JIRA_SUB_ISSUE_TYPE }}
  JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  JIRA_AUTH: "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}"
jobs:
  create_jira_issue:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get PR details
        id: pr-details
        run: |
          echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "description=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          echo "assignee=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "reviewers=${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}" >> $GITHUB_OUTPUT
      - name: Create Jira issue for assignee
        id: create-assigned-issue
        env:
          DESCRIPTION: ${{ steps.pr-details.outputs.description }}
          ASSIGNEE: ${{ steps.pr-details.outputs.assignee }}
          PR_NUMBER: ${{ steps.pr-details.outputs.number }}
          PR_TITLE: ${{ steps.pr-details.outputs.title }}
        run: |
          key=${{ env.ASSIGNEE }}
          echo "ASSIGNEE: ${ASSIGNEE}"
          assignee_id=$(echo '${{ secrets.JIRA_GITHUB_MAPPING }}' | jq -r --arg key "${{ env.ASSIGNEE }}" '.[$key]')
          echo "ASSIGNEE ID: ${assignee_id}"
          
          #Find all fields
          curl -s --request GET \
          --url "${{ env.JIRA_URL }}/rest/api/3/field" \
          --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
          --header "Content-Type: application/json" > all_fields.json
          git fetch origin master
          lines_changed=$(git diff --shortstat origin/master HEAD | awk '{print $1 + $4}')
          files_changed=$(curl -s --request GET \
          --url "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.v3+json" | jq '. | length')
          files_changed_field_id=$(jq -r --arg name "files_changed" '.[] | select(.name == "files_changed") | .id' all_fields.json)
          lines_changed_field_id=$(jq -r --arg name "lines_changed" '.[] | select(.name == "lines_changed") | .id' all_fields.json)
          echo "lines_changed = ${lines_changed}"
          echo "files_changed = ${files_changed}"
          echo "files_changed_field_id = ${files_changed_field_id}"
          echo "lines_changed_field_id = ${lines_changed_field_id}"
          curl -s -X POST \
          --url "${{ env.JIRA_URL }}/rest/api/3/issue/" \
          --header "Content-Type: application/json" \
          --header "Accept: application/json" \
          --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
          --data '{
            "fields": {
              "project": {
                "key": "'"${{ env.PROJECT_KEY }}"'"
              },
              "issuetype": {
                "name": "'"${{ env.ISSUE_TYPE }}"'"
              },
              "summary": "'"${GITHUB_REPOSITORY#${GITHUB_OWNER}}#${PR_NUMBER} - ${PR_TITLE}"'",
              "description": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": "'"${{ env.DESCRIPTION }}"'"
                      }
                    ]
                  }
                ]
              },
              "assignee": {
                "accountId": "'"${assignee_id}"'"
              },
              "'"${files_changed_field_id}"'": '${files_changed}',
              "'"${lines_changed_field_id}"'": '${lines_changed}'
            }
          }' > jira-issue.json
          
          # Parse issue key from Jira response
          cat jira-issue.json
          assignee_issue_key=$(cat jira-issue.json | jq -r '.key')
          echo "assignee-issue-key=${assignee_issue_key}" >> $GITHUB_OUTPUT
      - name: Create Jira issues for reviewers
        env:
          DESCRIPTION: ${{ steps.pr-details.outputs.description }}
          REVIEWERS: ${{ steps.pr-details.outputs.reviewers }}
          ASSIGNEE_ISSUE_KEY: ${{ steps.create-assigned-issue.outputs.assignee-issue-key }}
          PR_NUMBER: ${{ steps.pr-details.outputs.number }}
          PR_TITLE: ${{ steps.pr-details.outputs.title }}
        run: |
          for reviewer in $(echo ${{ env.REVIEWERS }} | tr ',' '\n'); do
            key=${reviewer}
            reviewer_id=$(echo '${{ secrets.JIRA_GITHUB_MAPPING }}' | jq -r --arg key "${reviewer}" '.[$key]')
            echo "Reviewer: ${reviewer_id}"
            curl -s -X POST \
            --url "${{ env.JIRA_URL }}/rest/api/2/issue/" \
            --header "Content-Type: application/json" \
            --header "Accept: application/json" \
            --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
            --data '{
              "fields": {
                "project": {
                  "key": "'"${{ env.PROJECT_KEY }}"'"
                },
                "parent": {
                  "key": "'"${{ env.ASSIGNEE_ISSUE_KEY }}"'"
                },
                "issuetype": {
                  "name": "'"${{ env.SUB_ISSUE_TYPE }}"'"
                },
                "summary": "'"${GITHUB_REPOSITORY#${GITHUB_OWNER}}#${PR_NUMBER} - ${PR_TITLE} - Reviewed by ${reviewer}"'",
                "assignee": {
                  "accountId": "'"${reviewer_id}"'"
                }
              }
            }' > jira-subtask.json
            cat jira-subtask.json
            SUBTASK_KEY=$(cat jira-subtask.json | jq -r '.key')
          done
  add_reviewer:
    if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REVIEWER_LOGIN: ${{ github.event.review.user.login }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get assignee ID
        id: pr-details
        run: |
          key=${{ github.event.pull_request.assignee.login }}
          assignee_id=$(echo '${{ secrets.JIRA_GITHUB_MAPPING }}' | jq -r --arg key "${{ github.event.pull_request.assignee.login }}" '.[$key]')
          echo "assignee_id=${assignee_id}" >> $GITHUB_ENV
          echo "reviewers=${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}" >> $GITHUB_OUTPUT
          echo "reviewers=${reviewers}"
      - name: Search
        id: search
        uses: tomhjp/gh-action-jira-search@v0.2.2
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          jql: 'project = "${{ env.PROJECT_KEY }}" AND text ~ "#${{ env.PR_NUMBER }} " AND assignee = "${{ env.assignee_id }}"'
      - name: Log
        run: echo "Found issue ${{ steps.search.outputs.issue }}"
      - name: Create reviewer subtask
        env:
          PARENT_ISSUE: ${{ steps.search.outputs.issue }}
          REVIEWERS: ${{ steps.pr-details.outputs.reviewers }}
        run: |
          for reviewer in $(echo ${{ env.REVIEWERS }} | tr ',' '\n'); do
            subtasks=$(curl -s --request GET \
             --url "${{ env.JIRA_URL }}/rest/api/3/issue/${{ env.PARENT_ISSUE }}/subtask" \
             --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
             --header "Accept: application/json")
            subtask_count=$(echo "$subtasks" | jq '.total')
          
            if [ "$subtask_count" -gt 0 ]; then
              assignees=$(echo "$subtasks" | jq -r '.issues[].fields.assignee.name')
              echo "assignees=${assignees}"
            else
              echo "assignees=null"
            fi
          
            if echo "$assignees" | grep -q "^${reviewer}$"; then
              echo "Subtask already created for reviewer: $reviewer"
            else
              echo "Subtask not yet created for reviewer: $reviewer. Creating subtask for reviewer."
              key=${reviewer}
                reviewer_id=$(echo '${{ secrets.JIRA_GITHUB_MAPPING }}' | jq -r --arg key "${reviewer}" '.[$key]')
                echo "Reviewer: ${reviewer_id}"
                curl -s -X POST \
                --url "${{ env.JIRA_URL }}/rest/api/3/issue/" \
                --header "Content-Type: application/json" \
                --header "Accept: application/json" \
                --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
                --data '{
                  "fields": {
                    "project": {
                      "key": "'"${{ env.PROJECT_KEY }}"'"
                    },
                    "parent": {
                      "key": "'"${{ env.PARENT_ISSUE }}"'"
                    },
                    "issuetype": {
                      "name": "'"${{ env.SUB_ISSUE_TYPE }}"'"
                    },
                    "summary": "'"${GITHUB_REPOSITORY#${GITHUB_OWNER}}#${PR_NUMBER} - ${PR_TITLE} - Reviewed by ${reviewer}"'",
                    "assignee": {
                      "accountId": "'"${reviewer_id}"'"
                    }
                  }
                }' > jira-subtask.json
                cat jira-subtask.json
                SUBTASK_KEY=$(cat jira-subtask.json | jq -r '.key')
            fi
          done
  approve_received:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REVIEWER_LOGIN: ${{ github.event.review.user.login }}
      ASSIGNEE_LOGIN: ${{ github.event.pull_request.user.login }}
    steps:
      - name: Get reviewer ID
        id: get-reviewer-id
        run: |
          key=${{ github.event.review.user.login }}
          echo "assignee=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          reviewer_id=$(echo '${{ secrets.JIRA_GITHUB_MAPPING }}' | jq -r --arg key "${{ github.event.review.user.login }}" '.[$key]')
          echo "reviewer_id=${reviewer_id}" >> $GITHUB_ENV
          echo "reviewer_id=${reviewer_id}"
      - name: Search
        id: search
        uses: tomhjp/gh-action-jira-search@v0.2.2
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          jql: 'project = "${{ env.PROJECT_KEY }}" AND text ~ "#${{ env.PR_NUMBER }} " AND assignee = "${{ env.reviewer_id }}"'
      - name: Log
        run: echo "Found issue ${{ steps.search.outputs.issue }}"
      - name: Get Transition ID
        id: get-transition-id
        run: |
          curl --request GET \
            --url "${{ env.JIRA_URL }}/rest/api/3/issue/${{ steps.search.outputs.issue }}/transitions" \
            --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
            --header "Accept: application/json" > transition.json
          cat transition.json
          transition_id=$(cat transition.json | jq -r '.transitions[] | select(.name == "Done") | .id')
          echo "transition_id=${transition_id}" >> $GITHUB_ENV
          echo "transition_id = ${transition_id}"
      - name: Change reviewer issue status
        run: |
          curl -s --request POST \
          --url "${{ env.JIRA_URL }}/rest/api/3/issue/${{ steps.search.outputs.issue }}/transitions" \
          --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --data '{
            "transition": {
              "id": "${{ env.transition_id }}"
            },
            "fields": {}
          }' > transition.json
          cat transition.json
      - name: Get changed files
        id: changed-files
        run: echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)" >> $GITHUB_OUTPUT
      - name: Update first or second review time
        run: |
          # Get the pull request number
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "PR_NUMBER=${PR_NUMBER}"
          echo "github repository=${{ github.repository }}"
          REVIEWS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")
          APPROVAL_COUNT_OVERALL=$(echo "${REVIEWS}" | jq '[.[] | select(.state == "APPROVED")] | length')
          APPROVAL_COUNT=$(echo "${REVIEWS}" | jq --arg username "${{ env.REVIEWER_LOGIN }}" '. | map(select(.user.login == $username and .state == "APPROVED")) | length')
          echo "APPROVAL_COUNT=${APPROVAL_COUNT}";
          REVIEWED_REVIEWERS=$(echo "${REVIEWS}" | jq -r '.[].user.login' | sort | uniq | wc -l)
          echo "REVIEWED_REVIEWERS=${REVIEWED_REVIEWERS}";
          
          response=$(curl -s --request GET \
            --url "${{ env.JIRA_URL }}/rest/api/3/issue/${{ steps.search.outputs.issue }}" \
            --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
            --header "Accept: application/json")
          parent_key=$(echo "$response" | jq -r '.fields.parent.key')
          echo "parent_key=${parent_key}"
          
          curl -s --request GET \
            --url "${{ env.JIRA_URL }}/rest/api/3/field" \
            --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
            --header "Content-Type: application/json" > all_fields.json
          
          first_review_time_field_id=$(jq -r --arg name "first_review_time" '.[] | select(.name == "first_review_time") | .id' all_fields.json)
          echo "first_review_time_field_id=${first_review_time_field_id}"
          
          second_review_time_field_id=$(jq -r --arg name "second_review_time" '.[] | select(.name == "second_review_time") | .id' all_fields.json)
          echo "second_review_time_field_id=${second_review_time_field_id}"
          
          # First review - update first_review_time field                    
          response=$(curl -s --request GET \
            --url "${{ env.JIRA_URL }}/rest/api/3/issue/${{ steps.search.outputs.issue }}" \
            --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
            --header "Accept: application/json")
          first_review_time=$(echo "$response" | jq -r ".fields.${first_review_time_field_id}")
          echo "first_review_time=$first_review_time"
          if [ "$APPROVAL_COUNT" == 1 ]; then
            curl -s --request PUT \
            --url "${{ env.JIRA_URL }}/rest/api/3/issue/${parent_key}" \
            --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data '{
              "fields":{
                "'"${first_review_time_field_id}"'": "'"$(date +'%Y-%m-%dT%H:%M:%S.000%z')"'"
              }
            }'
          fi
          
          # Second review - update second_review_time field          
          second_review_time=$(echo "$response" | jq -r ".fields.${second_review_time_field_id}")
          echo "second_review_time = ${second_review_time}"
          if [ "$APPROVAL_COUNT" == 2 ]; then
            curl -s --request PUT \
            --url "${{ env.JIRA_URL }}/rest/api/3/issue/${parent_key}" \
            --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }}" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data '{
              "fields": {
                "'"${second_review_time_field_id}"'": "'"$(date +'%Y-%m-%dT%H:%M:%S.000%z')"'"
              }
            }'
          fi
