name: Create Jira issue on PR open
on:
  pull_request:
    types: [opened]
jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    env:
      alchibekov: '5c2f993ed254b55db84cb3e1'
    steps:
      - name: Get PR details
        id: pr-details
        run: |
          echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "description=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          echo "assignee=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
      - name: Create Jira issue
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          ISSUE_TYPE: ${{ secrets.JIRA_ISSUE_TYPE }}
          JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
          DESCRIPTION: ${{ steps.pr-details.outputs.description }}
          ASSIGNEE: ${{ steps.pr-details.outputs.assignee }}
        run: |
          curl -s -X POST \
          --url "${JIRA_URL}/rest/api/2/issue/" \
          --header "Content-Type: application/json" \
          --header "Accept: application/json" \
          --user "${JIRA_AUTH}" \
          -d '{
              "fields": {
                  "project": {
                      "key": "'"${PROJECT_KEY}"'"
                  },
                  "issuetype": {
                      "name": "'"${ISSUE_TYPE}"'"
                  },
                  "summary": "'"${{ steps.pr-details.outputs.title }} - ${GITHUB_REPOSITORY#${GITHUB_OWNER}}#${{ github.event.pull_request.number }}"'",
                  "description": "'"${DESCRIPTION}"'",
                  "assignee": {
                    "accountId": ${{ env['${ASSIGNEE}'] }}
                  }
              }
          }'
