name: Create Jira issue on PR open
on:
  pull_request:
    types: [opened]
jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        id: pr-details
        run: |
          echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "DESCRIPTION=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          echo "ASSIGNEE=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
      - name: Create Jira issue
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          ISSUE_TYPE: ${{ secrets.JIRA_ISSUE_TYPE }}
          JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
        run: |
          curl -s -X POST \
          --url "${JIRA_URL}/rest/api/2/issue/" \
          --header "Content-Type: application/json" \
          --header "Accept: application/json" \
          --user "${JIRA_AUTH}" \
          -d '{
              "fields": {
                  "project": {
                      "key": "'"${PROJECT_KEY}"'"
                  },
                  "issuetype": {
                      "name": "'"${ISSUE_TYPE}"'"
                  },
                  "summary": "'"${{ env.TITLE }} - ${GITHUB_REPOSITORY#${GITHUB_OWNER}/}}#${{ github.event.pull_request.number }}"'"
                  "description": "'"${{ env.DESCRIPTION }}"'",
                  "assignee": {
                      "name": "'"${{ env.ASSIGNEE }}"'"
                  }
              }
          }'
